### ISSUE TITLE
error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by ashishkaransingh** [nathanielc/tick-prophet#1]
Thank you @nathanielc for the example, i was able to overcome the time format issue with the help of  prophet.py.

Now I am getting the following error if i use 30 days worth of data is this due to system's limitation? It works when with 1 day worth of data.

> Traceback (most recent call last):
> File "/home/user2/.local/lib/python2.7/site-packages/kapacitor/udf/agent.py", line 124, in _read_loop
> self.handler.end_batch(request.end)
> File "/etc/kapacitor/prophet.py", line 181, in end_batch
> self._agent.write_response(response)
> File "/home/user2/.local/lib/python2.7/site-packages/kapacitor/udf/agent.py", line 84, in write_response
> self._out.write(data)
> File "/usr/lib/python2.7/socket.py", line 328, in write
> self.flush()
> File "/usr/lib/python2.7/socket.py", line 307, in flush
> self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> ERROR:root:error processing request of type end: [Errno 32] Broken pipe
> Exception in thread Thread-4:
> Traceback (most recent call last):
> File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> self.run()
> File "/usr/lib/python2.7/threading.py", line 754, in run
> self._target(*self.args, **self._kwargs)
> File "/home/user2/.local/lib/python2.7/site-packages/kapacitor/udf/agent.py", line 135, in _read_loop
> self.write_response(response)
> File "/home/user2/.local/lib/python2.7/site-packages/kapacitor/udf/agent.py", line 82, in write_response
> encodeUvarint(self._out, len(data))
> File "/home/user2/.local/lib/python2.7/site-packages/kapacitor/udf/agent.py", line 158, in encodeUvarint
> return writer.write(chr(bits))
> File "/usr/lib/python2.7/socket.py", line 328, in write
> self.flush()
> File "/usr/lib/python2.7/socket.py", line 307, in flush
> self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> 
> Exception in thread Thread-3:
> Traceback (most recent call last):
> File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> self.run()
> File "/usr/lib/python2.7/threading.py", line 754, in run
> self._target(*self.args, **self._kwargs)
> File "/etc/kapacitor/prophet.py", line 202, in accept
> a.wait()
> File "/home/user2/.local/lib/python2.7/site-packages/kapacitor/udf/agent.py", line 68, in wait
> self._in.close()
> File "/usr/lib/python2.7/socket.py", line 283, in close
> self.flush()
> File "/usr/lib/python2.7/socket.py", line 307, in flush
> self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe]([url]([url](url)))

Tickscript:

> var interval = 5m
> 
> // Forecast specifies the amount of time to forecast into the future.
> // var forecast = 30d
> 
> // History defines the amount of historcal data to use.
> // var history = 4000d
> var history = 30d
> 
> var groupBy = [*]
> 
> 
> var changepointPriorScale = 0.05
> 
> 
> var uncertaintyIntervalWidth = 0.8
> 
> var forecastedDB = 'general_server'
> 
> // ForecastedRP is the name of a retention policy in which to store the forecasted result.
> // Default is autogen
> var forecastedRP = 'autogen'
> 
> var data = batch
>     |query('''
>     SELECT "Percent_Processor_Time" as value FROM "general_server"."autogen"."Processor" WHERE "instance"='_Total'
>     ''')
>         .period(history)
>         .every(5m)
>         .align()
>         .groupBy(groupBy)
>     @prophet()
>         // .periods(forecast / interval)
>         .periods(30)
>         .field('value')
>         .changepointPriorScale(changepointPriorScale)
>         .intervalWidth(uncertaintyIntervalWidth)
>     |log()
>     |influxDBOut()
>         .database(forecastedDB)
>         .retentionPolicy(forecastedRP)
>         .measurement('my_prophet_data_5mi_30dp')
>         .tag('model', 'prophet')

**Comment by ashishkaransingh** [comment]
Please let me know if you need additional information related to data structure etc.

**Comment by ashishkaransingh** [comment]
@nathanielc  
It is working with 30 days if i aggregate to over time 1h but am i missing any if i aggregated and pass it to prophet and not use raw data.

**Comment by gazon1** [comment]
Sorry for answering old question
I had the same error, you probably need to increase `timeout` option for udf in kapacitor config
